version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    environment:
      POSTGRES_DB: BankService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bank-app:
    build: .
    container_name: bank-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: BankService
      DB_USER: postgres
      DB_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8084"

volumes:
  postgres_data:
