spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
    password: 12345
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
      name: Bank
  liquibase:
    change-log: classpath:db/migration/changelog/15-01-changelog.yaml
server:
  port: 8084
jwt:
  jwt_secret: GovoryatVRyazaniEstbGribyiSGlazamiIhEdyatOniGlyadyat
  access_token_expiration_m: 30
  refresh_token_expiration_m: 4320
springdoc:
  api-docs.path: /v3/api-docs
  api-docs:
      enabled: true
      formats:  yaml
