spring:
  datasource:
    url: jdbc:postgresql://${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    application:
      name: Bank
  liquibase:
    change-log: classpath:db/migration/changelog/changelog-master.yaml
server:
  port: 8084
jwt:
  jwt_secret: GovoryatVRyazaniEstbGribyiSGlazamiIhEdyatOniGlyadyat
  access_token_expiration_m: 30
  refresh_token_expiration_m: 4320
springdoc:
  api-docs.path: /v3/api-docs
  api-docs:
      enabled: true
      formats:  yaml
